name: "Build"
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build Jacdac
        run: dotnet build .\Jacdac\Jacdac.csproj
      - name: Build Tests
        run: dotnet build .\Jacdac.Tests\Jacdac.Tests.csproj
      - name: Run tests
        run: dotnet test .\Jacdac.Tests\Jacdac.Tests.csproj
