name: "Build"
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - uses: microsoft/setup-msbuild@v1.1
      - name: NuGet restore
        run: dotnet restore
      - name: MSBuild Jacdac.Dev
        run: msbuild Jacdac.Dev.sln
      - name: Build Jacdac Debug
        run: dotnet build Jacdac.sln -c Debug
      - name: Build Jacdac Release
        run: dotnet build Jacdac.sln -c Release
      - name: Build Tests
        run: dotnet build .\Jacdac.Tests\Jacdac.Tests.csproj
      - name: Run tests
        run: dotnet test .\Jacdac.Tests\Jacdac.Tests.csproj
      - name: Semantic release
        run: npx -p=@semantic-release/git -p=@semantic-release/github -p=@semantic-release/exec -p=semantic-release-dotnet semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          NUGET_PUSH_URL: ${{ secrets.NUGET_PUSH_URL }}
