name: "Build"
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - uses: microsoft/setup-msbuild@v1.1
      - name: dotnet restore Jacdac.sln
        run: dotnet restore Jacdac.sln
      - name: msbuild restore Jacdac.sln
        run: msbuild -t:restore Jacdac.sln
      - name: MSBuild Jacdac Debug
        run: msbuild Jacdac.sln -p:Configuration=Debug
      - name: MSBuild Jacdac Release
        run: msbuild Jacdac.sln -p:Configuration=Release
      - name: Run tests
        run: dotnet test .\Jacdac.Tests\Jacdac.Tests.csproj
      - name: Semantic release
        run: npx -p=@semantic-release/git -p=@semantic-release/github -p=@semantic-release/exec -p=semantic-release-dotnet semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          NUGET_PUSH_URL: ${{ secrets.NUGET_PUSH_URL }}
